connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: criduino
  password: cri432

development:
  <<: *connection
  database: criduino_development

test:
  <<: *connection
  database: criduino_test

production:
  <<: *connection
  database: criduino_production
